update_dev:
  stage: build
  allow_failure: false
  only:
    refs:
      - dev
  before_script:
    - ssh boxy.rand.org "mkdir $CI_JOB_ID"
    - scp -r * boxy.rand.org:$CI_JOB_ID
  script:
  - ssh boxy.rand.org "cp -r $CI_JOB_ID/app/* /var/www/html/egoweb;
    mkdir -p /var/www/html/egoweb/assets;
    mkdir -p /var/www/html/egoweb/protected/runtime;"
  environment:
    name: dev
    url: http://egowebdev.rand.org/

update_alp_dev:
  stage: build
  allow_failure: false
  only:
    refs:
    - alpdev
  before_script:
  - ssh boxy.rand.org "mkdir $CI_JOB_ID"
  - scp -r * boxy.rand.org:$CI_JOB_ID
  script:
  - ssh boxy.rand.org "cp -r $CI_JOB_ID/app/* /var/www/html/alpegoweb;
    mkdir -p /var/www/html/alpegoweb/assets;
    mkdir -p /var/www/html/alpegoweb/protected/runtime;"
  environment:
    name: alp_dev
    url: $ALP_DEV_URL

test_alp_dev:
  stage: test
  allow_failure: false
  only:
    refs:
      - alpdev
  script:
    - cp -r ./test/wdio.conf.TEMPLATE.js ./test/wdio.conf.js
    - sed -i "s/CONFIG_ADMINUSER/$TEST_ALP_DEV_ADMIN_USER/g" ./test/wdio.conf.js
    - sed -i "s/CONFIG_ADMINPASSWORD/$TEST_ALP_DEV_ADMIN_PASSWD/g" ./test/wdio.conf.js
    - sed -i "s/CONFIG_INTERVIEWERUSER/$TEST_ALP_DEV_USER/g" ./test/wdio.conf.js
    - sed -i "s/CONFIG_INTERVIEWERPASSWORD/$TEST_ALP_DEV_PASSWD/g" ./test/wdio.conf.js
    - sed -i "s/phantomjs\.exe/\/home\/gitlab-runner\/\.local\/bin\/phantomjs/g" ./test/wdio.conf.js
    - sed -i "" "s~CONFIG_BASEURL~$ALP_DEV_URL~g" ./test/wdio.conf.js
    - cd ./test
    - npm install
    - java -jar /home/gitlab-runner/selenium-server-standalone-2.53.1.jar &
    - selenium_pid=$!
    - echo "selenium is running at $selenium_pid"
    - ./node_modules/.bin/wdio wdio.conf.js
    - kill $selenium_pid
  artifacts:
    reports:
      junit: ./build/junitresults/WDIO*.xml
  environment:
    name: alp_dev
    url: $ALP_DEV_URL

test_alp_dev_api:
  stage: test
  allow_failure: false
  only:
    refs:
      - alpdev
  script:
    - php ./test/APITest/testAPI.php $ALP_DEV_URL $ALP_DEV_PASSWD
  environment:
    name: alp_dev
    url: $ALP_DEV_URL

update_alp_prod:
  stage: deploy
  allow_failure: false
  only:
    refs:
    - alp
  before_script:
  - ssh smgolding.randcorp.org "mkdir $CI_JOB_ID"
  - scp -r * smgolding.randcorp.org:$CI_JOB_ID
  script:
  - ssh smgolding.randcorp.org "rm -rf backup;
    mkdir -p backup;
    yes | cp -rf  /var/www/alpegoweb backup;
    yes | cp -rf $CI_JOB_ID/app/* /var/www/alpegoweb;
    mkdir -p /var/www/alpegoweb/assets;
    mkdir -p /var/www/alpegoweb/protected/runtime;"
  environment:
    name: alp_prod
    url: http://alpegoweb.rand.org/
  when: manual