stages:
  - update_alp_dev
  - test_alp_dev

update_dev:
  allow_failure: false
  only:
    refs:
      - dev
  before_script:
    - ssh boxy.rand.org "mkdir $CI_JOB_ID"
    - scp -r * boxy.rand.org:$CI_JOB_ID
  script:
  - ssh boxy.rand.org "cp -r $CI_JOB_ID/app/* /var/www/html/egoweb;
    mkdir -p /var/www/html/egoweb/assets;
    mkdir -p /var/www/html/egoweb/protected/runtime;"
  environment:
    name: dev
    url: http://egowebdev.rand.org/

update_alp_dev:
  stage: update_alp_dev
  allow_failure: false
  only:
    refs:
    - alpdev
  before_script:
  - ssh boxy.rand.org "mkdir $CI_JOB_ID"
  - scp -r * boxy.rand.org:$CI_JOB_ID
  script:
  - ssh boxy.rand.org "cp -r $CI_JOB_ID/app/* /var/www/html/alpegoweb;
    mkdir -p /var/www/html/alpegoweb/assets;
    mkdir -p /var/www/html/alpegoweb/protected/runtime;"
  environment:
    name: alp_dev
    url: http://alpegowebdev.rand.org/

test_alp_dev_api:
  stage: test_alp_dev
  allow_failure: false
  script:
    - php ./test/APITest/testAPI.php $ALP_DEV_URL $ALP_DEV_PASSWD

update_alp_prod:
  allow_failure: false
  only:
    refs:
    - alp
  before_script:
  - ssh smgolding.randcorp.org "mkdir $CI_JOB_ID"
  - scp -r * smgolding.randcorp.org:$CI_JOB_ID
  script:
  - ssh smgolding.randcorp.org "rm -rf backup;
    mkdir -p backup;
    yes | cp -rf  /var/www/alpegoweb backup;
    yes | cp -rf $CI_JOB_ID/app/* /var/www/alpegoweb;
    mkdir -p /var/www/alpegoweb/assets;
    mkdir -p /var/www/alpegoweb/protected/runtime;"
  environment:
    name: alp_prod
    url: http://alpegoweb.rand.org/
  when: manual